# Generated by Django 3.1 on 2020-11-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
        ('users', '0002_auto_20201128_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='classroom',
            field=models.ManyToManyField(blank=True, related_name='classroom', to='classrooms.Classroom'),
        ),
    ]
