# Generated by Django 3.1 on 2020-11-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0003_auto_20201128_2358'),
        ('users', '0005_auto_20201128_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='waiting',
            field=models.ManyToManyField(blank=True, related_name='approve', to='classrooms.Classroom'),
        ),
    ]
