# Generated by Django 3.1 on 2020-11-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0004_randomperson'),
        ('users', '0006_student_waiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='picked',
            field=models.ManyToManyField(blank=True, related_name='randomperson', to='classrooms.RandomPerson'),
        ),
    ]
