# Generated by Django 3.1 on 2020-11-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0005_auto_20201129_1923'),
        ('users', '0007_student_picked'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='picked',
            field=models.ManyToManyField(blank=True, related_name='randomperson_t', to='classrooms.RandomPerson'),
        ),
    ]
