# Generated by Django 3.1 on 2020-11-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_classroom_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
