# Generated by Django 3.1 on 2020-11-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0003_auto_20201128_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=150, null=True)),
                ('user_email', models.CharField(max_length=150, null=True)),
                ('picked_email', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
