# Generated by Django 3.1 on 2020-11-29 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0004_randomperson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='randomperson',
            old_name='picked_email',
            new_name='picked_name',
        ),
        migrations.RenameField(
            model_name='randomperson',
            old_name='user_email',
            new_name='user_name',
        ),
    ]
